application: devfest-norte
version: 1
runtime: php55
api_version: 1

handlers:
- url: /bootstrap
  static_dir: bootstrap

- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /less
  static_dir: less

- url: /.*
  script: index.html
